language: c
sudo: false
os:
  - linux
  - osx

before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh

script:
  - asdf plugin-add julia https://github.com/nverno/asdf-julia
  - asdf list-all julia
  - asdf plugin-test julia https://github.com/nverno/asdf-julia.git
